CREATE TABLE BIGDATA_GITHUB.RAW.FOLLOWERS (
    follower_login INTEGER PRIMARY KEY,   
    user_login VARCHAR,
    user_id INTEGER,

    FOREIGN KEY (user_id) REFERENCES BIGDATA_GITHUB.RAW.GITHUB_MAIN(id),
    FOREIGN KEY (user_login) REFERENCES BIGDATA_GITHUB.RAW.GITHUB_MAIN(login)
);
